### ISSUE TITLE
Grasshopper is not responding

### ISSUE THREAD

**Issue by GonzaloNavarroMunoz** [diff-arch/Tapeworm#2]
Hello!

First of all, congratulations on the development of the plugin! I think it is quite useful. 

I am opening this issue as I am experiencing unexpected behavior from GH when I tried to follow the example described in https://www.youtube.com/watch?v=FfgvohowRhw. The problem is that as soon as I connect the "File Path" component, linked to the first image of the series, to the "Source Path" input, GH stops responding. 

![image](https://user-images.githubusercontent.com/50489727/129036773-f0eb2cb7-994c-4337-a1c6-f3ef0d187e0c.png)

I have downloaded the plugin, saving the user objects and python files. Additionally, I have copied the 4.4 version release essentials (https://www.gyan.dev/ffmpeg/builds/) on my local "\\C:" as indicated. The images I am using are the ones below which are in JPG format. I have a Rhino 6 version up to date and a GH version of 1.0.0007. 

I would appreciate any help.

Thanks very much! 

![2103032014](https://user-images.githubusercontent.com/50489727/129036809-1622fa4e-62ae-4334-a52b-524e8ade8c06.jpg)
![2103032018](https://user-images.githubusercontent.com/50489727/129036813-722935a0-0dd9-4dce-a10e-8b63226519fe.jpg)
![2103032022](https://user-images.githubusercontent.com/50489727/129036814-a3896aa0-6bbb-490b-a47b-c361200211c4.jpg)
![2103032026](https://user-images.githubusercontent.com/50489727/129036817-11e974dd-6929-4973-98e0-de290801dd5c.jpg)
![2103032030](https://user-images.githubusercontent.com/50489727/129036819-034f4d11-2bb6-4c09-83b9-72da90dbacd0.jpg)

**Comment by diff-arch** [comment]
Hi Gonzalo,

I've downloaded your 5 sample images and one thing that immediately caught my attention is the file naming.
Were your images called the same when you tried Tapeworm?

If so, the issue is that the filename parser can't derive an order, because it looks for a number sequence that's iteratively changing (like counting), whereas your filenames suggest that your image sequence has more than one, which is not supported, and in reality doesn't seem to have any.

![Screenshot 2021-08-11 at 16 32 00](https://user-images.githubusercontent.com/10381015/129048353-4185e620-ca82-4e11-9794-cd3433aba04d.png)

If this is the case,  try renaming your files!

**Comment by GonzaloNavarroMunoz** [comment]
Hi diff-arch,

Thanks very much for your comment. In my computer, the images have different names (numbers) but these numbers are not consecutive. 

![image](https://user-images.githubusercontent.com/50489727/129149490-f920b969-5966-4766-bf53-efc2e8913ec3.png)

That was causing the problem as you indicated. I have changed those names to be consecutive numbers and now it works perfectly.

However, those five images were only a test. In reality, I would like to use thousands of images that I have stored to create a video. I see two problems:

- Those images are not named with consecutive numbers. Thus I would need to batch rename them. But when I try to link the "File Path" (from the "first" of those images) to the "Source Path" input, to use the batch renaming component from Tapeworm, I encounter the problem of GH not responding due to non-consecutive naming. 
- The non-consecutive name is larger than the capacity of Int32. 

![image](https://user-images.githubusercontent.com/50489727/129150698-089024b7-b4f0-45da-9857-eee7a01cc55e.png)


Would there be any way of using the Tapeworm components for these renaming tasks given the circumstances? 

Thanks very much!

**Comment by diff-arch** [comment]
Hi,

OK, the non-consecutive file naming is surely the issue. You need to have a consecutive number sequence, but it shouldn't matter if there are a couple of missing images.
However, Tapeworm shouldn't crash Rhino. I'll investigate it. Thanks for reporting that and sharing a relevant example!

Currently, the BatchRename component that comes with Tapeworm only allows you to rename recognized, parsed image sequences. It thus needs an IO instance as input. This is for security reasons. We don't want anybody to for instance rename their whole file system.
It's on our list to maybe allow renaming of alphabetically sorted files, however it's not a priority for now.
You can look for a third-party application to rename your files, but as far as I know you can even do it with Windows.
