### ISSUE TITLE
Start frame shouldn't be relative to the name

### ISSUE THREAD

**Issue by MaesAntoine** [diff-arch/Tapeworm#4]
After batch renaming, the name started at 8000 (by mistake).

Tapeworm wanted me to specify that the first frame was 8000, where it should just be 0 (the first frame of the sequence).

![image](https://user-images.githubusercontent.com/39027094/149298903-d287795a-3e03-4ad1-b29d-5b7c82f4d5f4.png)

**Comment by diff-arch** [comment]
Misunderstanding about the functionality of the **StartFrame** input of the Frames-GIF Settings component, which chooses the start frame by frame number, not by count.
